### ISSUE TITLE
Making contrast comparing cell lines (for a treatment effect)

### ISSUE THREAD

**Issue by duongch4** [statOmics/MSqRob#17]
Hi team,

I would like to ask a question regarding making contrasts in the package.

Following the given instruction, my model is:
protLM <- fit.model(proteins, response = "quant_value",
                                fixed = c("treatment"), random = c("biorep", "run", "Sequence"),
                                add.intercept = TRUE, weights = "Huber"))

where "treatment" has 3 levels: "T1", "T2", "T3"
"biorep" has 3 levels: "G1", "G2", "G3" (3 different cell lines)

To compare any 2 treatments across all cell lines, I did as instructed in the vignette:
L <- makeContrast(contrasts = c("treatmentT1 - treatmentT2"), levels = c("treatmentT1", "treatmentT2", "treatmentT3"))

More than that, I would like to know:
1. Whether one cell line is more "responsive" to a treatment than another cell line. So something like this:  [ (treatmentT1 - treatmentT2) in biorepG1 ] compared to [ (treatmentT1 - treatmentT2) in biorepG2 ]
2. Specifically for a cell line, what are the differentially expressed genes between any 2 treatments. So something like this: (treatmentT1 - treatmentT2) in biorepG1 only

Would you please show me how to write those contrasts? 
Thank you very much for your time.

Best regards,
Chi

**Comment by ghost** [comment]
Dear Chi

To avoid confusion, let us call "cell" the effect of cell line. 
Do you then have multiple biological repeats per cell type (i.e. did you redo the experiment a couple of times with the same cell lines)? Note: this is not the same as technical repeats (i.e. running the same sample multiple times on the mass spec!)

**1. If you do have multiple biological repeats:**

Just make a new combined factor called e.g. "treatment_cell" with the following levels:

T1G1, T1G2, T1G3, T2G1, T2G2, T2G3, T3G1, T3G2, T3G3

I would then fit the model as follows:

protLM <- fit.model(proteins, response = "quant_value", fixed = c("treatment_cell"), random = c("biorep", "run", "Sequence"), add.intercept = TRUE, weights = "Huber"))

Note: "biorep" is only needed if you also have multiple technical repeats per biological repeat, you can omit it if your runs are also your biological repeats. Then you can make your contrast matrix as follows:

L <- makeContrast(contrasts = c(
  "(treatment_cellT1G1/3+treatment_cellT1G2/3+treatment_cellT1G3/3)-(treatment_cellT2G1/3+treatment_cellT2G2/3+treatment_cellT2G3/3)",
  "(treatment_cellT1G1-treatment_cellT2G1)-(treatment_cellT1G2-treatment_cellT2G2)",
  "treatment_cellT1G1-treatment_cellT2G1"),
  levels = c("treatment_cellT1G1", "treatment_cellT1G2", "treatment_cellT1G3", "treatment_cellT2G1", "treatment_cellT2G2", "treatment_cellT2G3", "treatment_cellT3G1", "treatment_cellT3G2", "treatment_cellT3G3"))

Explanation:

*The first row of your L matrix:
"(treatment_cellT1G1/3+treatment_cellT1G2/3+treatment_cellT1G3/3)-(treatment_cellT2G1/3+ treatment_cellT2G2/3+treatment_cellT2G3/3)"
-> this tests what you wanted to test before: is there on average over the three cell lines a difference between the effect of treatment 1 and the effect of treatment 2

*The second row of your L-matrix:
"(treatment_cellT1G1-treatment_cellT2G1)-(treatment_cellT1G2-treatment_cellT2G2)"
-> this tests whether the difference in effect between treatment 1 and treatment 2 is different between cell line 1 and cell line 2.

*The last row of your L-matrix:
"treatment_cellT1G1-treatment_cellT2G1"
-> this tests whether there is a difference in effect between treatment 1 and treatment 2 for cell line 1 only.

**2. If you do not have biological repeats**

In this case you cannot assess any cell line-specific effects, because you only have one repeat per cell line. Here, you should use your cell lines as biological replicates. You could fit your model as follows:

protLM <- fit.model(proteins, response = "quant_value", fixed = c("treatment"), random = c("cell", "run", "Sequence"), add.intercept = TRUE, weights = "Huber"))

You can then only answer your first research question with the matrix you already constructed:

L <- makeContrast(contrasts = c("treatmentT1 - treatmentT2"), levels = c("treatmentT1", "treatmentT2", "treatmentT3"))

It is then impossible to know whether one cell line is more responsive to treatment than another, because you have only one observation for each protein, so you don't have any idea of the biological variability within a cell line. You could of course take a look at fold changes, but do note that big fold changes alone can also be due to the fact that some proteins are sometimes more abundant and if you repeat the experiment, they could be a bit less abundant. Without biological replicates, you are essentially blind for this.

Idem for the third research question: if you don't have any biological repeat, you can report a size difference, but you don't have any estimate of the variability within a cell line.

In any case, please note that for the last two research questions, if you don't have real biological repeats, you can only do exploratory data analysis and it would be wrong to report p-values because p-values imply that you have real biological replication.

I hope this makes it a little bit more clear, if not, please do not hesitate to reply here.
Good luck with your analysis!

Cheers

Ludger

**Comment by duongch4** [comment]
Dear Ludger, 

Thank you very much for your detailed response. To be absolutely clear about the terminology, this is the experiment design: **27** cell pellets were received (so these are the 27 (technical) runs, am I correct?). I have 3 different cell lines (from 3 different people) and 3 drug treatments; and 3 replicates per cell line per treatment (i.e. 3x3x3 = 27). A picture representing the experiment is attached.
![image](https://user-images.githubusercontent.com/14342042/27592001-650da0e6-5b21-11e7-95d2-2b479089d7db.png)

The experiment annotation from R is:
> exp_annotation
               run              treatment     biorep
1   G561_GSK591_R1    GSK591   G561
2   G561_GSK591_R2    GSK591   G561
3   G561_GSK591_R3    GSK591   G561
4   G561_LLY283_R1    LLY283   G561
5   G561_LLY283_R2    LLY283   G561
6   G561_LLY283_R3    LLY283   G561
7  G561_SGC2096_R1   SGC2096   G561
8  G561_SGC2096_R2   SGC2096   G561
9  G561_SGC2096_R3   SGC2096   G561
10  G564_GSK591_R1    GSK591   G564
11  G564_GSK591_R2    GSK591   G564
12  G564_GSK591_R3    GSK591   G564
13  G564_LLY283_R1    LLY283   G564
14  G564_LLY283_R2    LLY283   G564
15  G564_LLY283_R3    LLY283   G564
16 G564_SGC2096_R1   SGC2096   G564
17 G564_SGC2096_R2   SGC2096   G564
18 G564_SGC2096_R3   SGC2096   G564
19  G583_GSK591_R1    GSK591   G583
20  G583_GSK591_R2    GSK591   G583
21  G583_GSK591_R3    GSK591   G583
22  G583_LLY283_R1    LLY283   G583
23  G583_LLY283_R2    LLY283   G583
24  G583_LLY283_R3    LLY283   G583
25 G583_SGC2096_R1   SGC2096   G583
26 G583_SGC2096_R2   SGC2096   G583
27 G583_SGC2096_R3   SGC2096   G583

To my understanding, since we are dealing with different cell lines (which are biologically distinct) of the same organism (human), the cell lines are biological replicates (so strictly speaking we have 3 biological replicates). 
Then I would say the replicates within each cell lines (3 per cell line per treatment, in this case) are strictly technical repeats.
However, it seems that you call the replicates within each cell line biological replicates. So according to the aforementioned experimental design, am I correct to say yes there are "biological repeats"? Please correct me on these terminologies.

Also, should I change the values of the "biorep" column? Should it be something like: b_1, b_1, b_1, b_2, b_2, b_2, b_3(x3), b_4(x3), b_5(x3), b_6(x3), b_7(x3), b_8(x3), b_9(x3)?

Thank you very much for your help.

Chi

**Comment by ludgergoeminne** [comment]
Dear Chi

Sorry for the late answer, I was very busy this week.

"Biological replicates" just means that you applied your treatment on different subjects, i.e. you cultured the three cell lines, gave them your treatments, did the experiment and then repeated this whole procedure another two times. "Technical replicates" is a term to denote replicates that came from the same biological sample, but just originated from putting the sample multiple times on the mass spec. If you only have technical replicates, you cannot do valid statistics because you wouldn't have any idea of the relevant biological variability.

If you want to know more about replication, you can also always read the paper on replication in the Nature methods series "Points of significance":
https://www.nature.com/nmeth/journal/v11/n9/full/nmeth.3091.html

Therefore, I would call what you call "biorep", call "cell" instead. If I understand correctly, each cell line is from another person, right? This means that cell line and person coincide perfectly. You are correct that the runs are often technical repeats, but in your case, since you only put each sample on the mass spec once, they perfectly coincide with your biological repeats. I would then give your annotation file only two columns, as follows:

run treatment_cell
1 G561_GSK591_R1 GSK591_G561
2 G561_GSK591_R2 GSK591_G561
3 G561_GSK591_R3 GSK591_G561
4 G561_LLY283_R1 LLY283_G561
5 G561_LLY283_R2 LLY283_G561
6 G561_LLY283_R3 LLY283_G561
7 G561_SGC2096_R1 SGC2096_G561
8 G561_SGC2096_R2 SGC2096_G561
9 G561_SGC2096_R3 SGC2096_G561
10 G564_GSK591_R1 GSK591_G564
11 G564_GSK591_R2 GSK591_G564
12 G564_GSK591_R3 GSK591_G564
13 G564_LLY283_R1 LLY283_G564
14 G564_LLY283_R2 LLY283_G564
15 G564_LLY283_R3 LLY283_G564
16 G564_SGC2096_R1 SGC2096_G564
17 G564_SGC2096_R2 SGC2096_G564
18 G564_SGC2096_R3 SGC2096_G564
19 G583_GSK591_R1 GSK591_G583
20 G583_GSK591_R2 GSK591_G583
21 G583_GSK591_R3 GSK591_G583
22 G583_LLY283_R1 LLY283_G583
23 G583_LLY283_R2 LLY283_G583
24 G583_LLY283_R3 LLY283_G583
25 G583_SGC2096_R1 SGC2096_G583
26 G583_SGC2096_R2 SGC2096_G583
27 G583_SGC2096_R3 SGC2096_G583

And then fit your model as:

protLM <- fit.model(proteins, response = "quant_value", fixed = c("treatment_cell"), random = c("run", "Sequence"), add.intercept = TRUE, weights = "Huber"))

and use the contrasts I described in my previous answer on under **"1. If you do have multiple biological repeats"**.

Does this help you a bit further?

Please not that I will go on holidays soon, so if you still have any questions that require a quick answer, please ask them as soon as possible!

Cheers

Ludger

**Comment by duongch4** [comment]
Dear Ludger,

Thank you very much for the clarification. It is clear to me now. I really appreciate it.
Have a wonderful holiday! 

Best regards,

Chi

**Comment by ludgergoeminne** [comment]
Dear Chi

You're most welcome!
I'm going to close this issue now, but if you would have any further questions
or you doubt anything concerning MSqRob, please don't hesitate to contact me!

Cheers

Ludger
