### ISSUE TITLE
Can't analyse my moff .tab file

### ISSUE THREAD

**Issue by davidserv** [statOmics/MSqRob#32]
Are moFF output files fully supported in MSqRob ? Everytime I click on "Start the analysis" button I get the error:

*Make sure that exactly one column in the experiment annotation has elements equal to the mass spec run names in the data. Maybe one of the following columns has an error in at least one of its elements: run, conditions.*

Attached are both the peptide summary and the annotation files I use. Below are the parameters I selected for the search:

-Group by: prot
-Fixed effects: genotype
-Random effects: peptide & run
No additional columns and no filter columns.

David S.
[peptide_summary_intensity_moFF_run.txt](https://github.com/statOmics/MSqRob/files/1377640/peptide_summary_intensity_moFF_run.txt)
[project_experimental_annotation.xlsx](https://github.com/statOmics/MSqRob/files/1377641/project_experimental_annotation.xlsx)

**Comment by ludgergoeminne** [comment]
Dear David

The error is produced because the names of your runs do not correspond your moFF filenames.
Your runs should be called "qExHF01_03201_HILIC_11" and "qExHF01_03196_HILIC_5" (i.e. everything after the "sumIntensity_" in your peptides file). I have included a corrected experimental annotation file.

That being said, unless you only uploaded part of your experiment, "genotype" is an unnecessary addition in your case, because you only have one WT run and one KO run, so "genotype" is essentially the same as your "run".

Third, and most importantly, if this is your full experiment, it doesn't make any sense to do statistics on this dataset because you have no biological repeats. With this experiment you are unable to assess if any difference you see is simply due to random chance (e.g. some proteins will be a bit more or less abundant in your KO sample for reasons that have nothing to do with your treatment, or, in this case, even run effects can have a profound effect on your results!).

[project_experimental_annotation.xlsx](https://github.com/statOmics/MSqRob/files/1379224/project_experimental_annotation.xlsx)

**Comment by davidserv** [comment]
Good points indeed. Fortunately for me this data is only for test to play around with the software, which is by the way a really convenient one ! So I don't really care about the quality of this analysis.

Anyway, it works correctly now, many thanks.

David S.
